stages:
  - deploy
deploy_job:
  stage: deploy
  script:
    - |
      rsync -az -e "ssh -i ~/.ssh/runner" --exclude=".git/" --exclude=".gitlab-ci.yml" --delete ./ $webserver:$wwwpath/swiftsites.fyi
      ssh -i ~/.ssh/runner $webserver "
        $wwwpath/swiftsites.fyi/misc/articlegen.sh $wwwpath/swiftsites.fyi/articles/
        $wwwpath/swiftsites.fyi/misc/sitelistgen.sh $wwwpath/swiftsites.fyi/csv/
        rm -f $wwwpath/swiftsites.fyi/articles/template.html
        rm -f $wwwpath/swiftsites.fyi/articles/*.ikmd
        rm -f $wwwpath/swiftsites.fyi/README.md
        rm -f $wwwpath/swiftsites.fyi/LICENSE
        echo \"\$(date +'%B %d %Y %I:%M %p')\" > $wwwpath/swiftsites.fyi/misc/last_updated.txt
      "
      rsync -az -e "ssh -i ~/.ssh/runner" --exclude=".git/" --exclude=".gitlab-ci.yml" --delete ./csv/*.csv $cdnserver:$cdnpath/swiftsites.fyi/csv/
      ssh -i ~/.ssh/runner $webserver "rm -f $wwwpath/swiftsites.fyi/csv/*.csv"